# Choose an optional name for the datacenter
global:
  enabled: true
  datacenter: mydc
  image: "consul@sha256:3959d1fd97fdb82a9ec726e4dcbfe55600b5e382094c9ac3b720cad345972245"
  imageK8S: "blakec/consul-k8s:0.10.1"

# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: 'NodePort'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true
  imageEnvoy: "pranaypratyush/envoy-arm32v7:firsttry"

client:
  enabled: true
  grpc: true

dns:
  enabled: true

syncCatalog:
  enabled: true
  toK8S: false

# Use only one Consul server for local development
server:
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
