apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-client

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-client
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "nginx:1234"
spec:
  containers:
    # This name will be the service name in Consul.
    - name: nginx-client
      image: lucashalbert/curl@sha256:649fd48107ec7a3bdedb9ab7e43704a3524f1b3a10e0550fe3475a0f03fdac0b
      # Just spin & wait forever, we'll use `kubectl exec` to demo
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
   # If ACLs are enabled, the serviceAccountName must match the Consul service name.
  serviceAccountName: nginx-client
